package ParkingLot.commands;

import ParkingLot.controllers.BillController;
import ParkingLot.dtos.requestDto.BillGenerateRequestDto;
import ParkingLot.dtos.responseDto.BillGenerateResponseDto;
import ParkingLot.reposetories.BillReposetory;
import ParkingLot.reposetories.TicketReposetory;
import ParkingLot.services.BillService;
import ParkingLot.strategies.feesCalculatorStrategy.FeesCalculatorStrategy;

import java.util.Scanner;

public class GenerateBillCommand implements Command {
    private BillController billController;
    private Scanner sc;

    public GenerateBillCommand(TicketReposetory ticketReposetory, BillReposetory billReposetory, FeesCalculatorStrategy feesCalculatorStrategy) {
        this.billController = new BillController(new BillService(ticketReposetory, billReposetory, feesCalculatorStrategy));
        sc = new Scanner(System.in);
    }
    @Override
    public void execute(){
        BillGenerateRequestDto requestBill = new BillGenerateRequestDto();
        System.out.println("Enter the Ticket Id: ");
        String ticketIdInput = sc.next();
        Long ticketId = Long.parseLong(ticketIdInput);
        requestBill.setTicketID(ticketId);
        BillGenerateResponseDto responseBill = billController.billGenerate(requestBill);
        System.out.println("Your total bill amount: " + responseBill.getAmount());
        System.out.println("Your bill generated at GateNo: " + responseBill.getGateNo());
        System.out.println("Your exit time: " + responseBill.getExitTime());
        System.out.println("Your bill generated by: " + responseBill.getOperatorName());
    }

    @Override
    public boolean matches(String input) {
        if (input.equals(CommandKeywords.GENERATE_BILL)){
            return true;
        }
        return false;
    }
}
